version: 0.2

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'
    - 'node_modules/**/*'  # 缓存项目中的 node_modules 目录

phases:
  pre_build:
      commands:
        - echo "Pre-build phase"
        - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain paytend-domain --domain-owner 144523794490 --region eu-central-1 --query authorizationToken --output text`
        - echo $CODEARTIFACT_AUTH_TOKEN
        - |
          cat > /root/.m2/settings.xml <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
            <localRepository>/root/.m2/repository</localRepository>

            <servers>
              <server>
                <id>paytend-domain-paytend-repo</id>
                <username>aws</username>
                <password>${CODEARTIFACT_AUTH_TOKEN}</password>
              </server>
            </servers>

            <mirrors>
              <mirror>
                <id>paytend-domain-paytend-repo</id>
                <mirrorOf>paytend-domain-paytend-repo</mirrorOf>
                <url>https://paytend-domain-144523794490.d.codeartifact.eu-central-1.amazonaws.com/maven/paytend-repo/</url>
              </mirror>
            </mirrors>

            <profiles>
              <profile>
                <id>paytend-domain-paytend-repo</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <repositories>
                  <repository>
                    <id>spring-snapshots</id>
                    <name>Spring Snapshots</name>
                    <url>https://repo.spring.io/snapshot</url>
                    <releases>
                      <enabled>false</enabled>
                    </releases>
                  </repository>
                  <repository>
                    <id>spring-milestones</id>
                    <name>Spring Milestones</name>
                    <url>https://repo.spring.io/milestone</url>
                    <snapshots>
                      <enabled>false</enabled>
                    </snapshots>
                  </repository>
                  <repository>
                    <id>paytend-domain-paytend-repo</id>
                    <url>https://paytend-domain-144523794490.d.codeartifact.eu-central-1.amazonaws.com/maven/paytend-repo/</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>

            <activeProfiles>
              <activeProfile>paytend-domain-paytend-repo</activeProfile>
            </activeProfiles>
          </settings>
          EOL

  install:
    runtime-versions:
      nodejs: 18

    commands:
        - echo "Installing React dependencies..."
        - npm run bootstrap

  build:
    commands:
        - echo "Building React APP..."
        - npm run build
        - echo "Installing Maven dependencies..."
        - mvn clean install
        - echo "Building Maven project..."
        - mvn package -DskipTests;

  post_build:
    commands:
      - echo "Syncing files to repositories"
      - mvn deploy -Pprod
